baseURL = 'https://example.org/'
# locale = 'en-us'
title = 'JP'

# Markup configs
[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
    guessSyntax = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]




# Navbar menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    [menu.main.params]
      alt = "Principio"

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
    [menu.main.params]
      alt = "Sobre Yo"

  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3
    [menu.main.params]
      alt = "Proyectos"

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4
    [menu.main.params]
      alt = "Contacto"








[module]
  [module.hugoVersion]
    extended = true
    min = "0.147.0"

[pagination]
  pagerSize = 6



[params]
  description = "JP - Portfolio - Portafolio"
  author = "Jordan Parra"

  theme_toggle = true
  # search = true
  # favicon = "/favicon.ico"
  math = false

  # hero_cta = "Explore Demo"
  # hero_cta_link = "/posts"

  footer_desc_en = ["Computer Data Professional","International Developer"]
  footer_desc_es = ["Professional en Datos Computacional","Desarrollador Internacional"]
  # copyright = "Demo site for Kawaii theme."

  [[params.social]]
    name = "github"
    url = "https://github.com/jp21bp"

  [[params.social]]
    name = "email"
    url = "https://gmail.com/peujah65@gmail.com"


  [[params.footer_links]]
    name = "Project 1"
    url = "/projects/project-1"
    alt = "Proyecto 1"

  [[params.footer_links]]
    name = "Resume"
    url = "/about"
    alt = "Resumen"


  #[[params.featured_sections]]
   # title = "Beautiful Design"
    #description = "Experience modern web design with kawaii aesthetics and smooth animations"
   # icon = "✨"
   # link = "/posts"





[outputs]
  # home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]








